version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-security:
        applies-to: security-updates
        patterns:
          - '*'
      npm-patch-minor:
        applies-to: version-updates
        update-types:
          - minor
          - patch
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
